{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyoubo",
    "module": "ManaitaPlus",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ManaitaPlus-2.0.1.jar",
          "url": "ManaitaPlus-2.0.1.jar",
          "size": 403629,
          "sha512": "9a31e0c3feaa11526dd3cf286016f64bdfc2daa6187615364da94921063e50830642f1e913fc20f6e2f644d767874a89e0e1702ef5f3254664c99ad7404e2e5a",
          "sha256": "a87855d9c576ee0b12a0855094fbf3aa5a943ae8cfb9cb30433eee7016a796ae",
          "sha1": "4be9b57f219ff6caade3603e548949235d8fbe09",
          "md5": "1f7ae5b83747699895b8b7642f19ea54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.19_mapped_official_1.20.1_at_7282289405b3da0334059ab7cc69e3d7eb083d10"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "strictly": "15.8.2.26_mapped_official_1.20.1",
            "requires": "15.8.2.26_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "ManaitaPlus-2.0.1.jar",
          "url": "ManaitaPlus-2.0.1.jar",
          "size": 403629,
          "sha512": "9a31e0c3feaa11526dd3cf286016f64bdfc2daa6187615364da94921063e50830642f1e913fc20f6e2f644d767874a89e0e1702ef5f3254664c99ad7404e2e5a",
          "sha256": "a87855d9c576ee0b12a0855094fbf3aa5a943ae8cfb9cb30433eee7016a796ae",
          "sha1": "4be9b57f219ff6caade3603e548949235d8fbe09",
          "md5": "1f7ae5b83747699895b8b7642f19ea54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ManaitaPlus-2.0.1-sources.jar",
          "url": "ManaitaPlus-2.0.1-sources.jar",
          "size": 255378,
          "sha512": "db93d4a89ab65b068fb7a2a130073aa2e05fc455a50cf2c11cbd0b395ef55fe2c97a73688ba92d67db641f2204613c84b898f326aee9d06f5ebffb507eb65d0a",
          "sha256": "b7d6954665beb12b1f96efe579c647f2c374bbfdadfea257f0101c1b3fca4018",
          "sha1": "038db9949f341c823066ab911fd750cdd89d0b2e",
          "md5": "65779e59a5e7e8cf38924370e002e7cd"
        }
      ]
    }
  ]
}
