{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyoubo",
    "module": "manaita_plus_general",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "manaita_plus_general-2.0.1.jar",
          "url": "manaita_plus_general-2.0.1.jar",
          "size": 397256,
          "sha512": "df0389019b67bda6429d5812289de37b9d7d175683b622351d16cdc4fe94fffe51a5d79a207c0daa39b920513c257423699939493095fdcfa90794ee32e210d7",
          "sha256": "970f9bbe1df8742f1c7b085ccb485d650cbdf23f5e409bbd8c0a88f0902cba7e",
          "sha1": "4603e3ee97c0706c2a850a5856b8b3823af1d348",
          "md5": "918af88e594737c65ead07856d006db6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.8+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "jei-238222",
          "version": {
            "requires": "7920913"
          }
        }
      ],
      "files": [
        {
          "name": "manaita_plus_general-2.0.1.jar",
          "url": "manaita_plus_general-2.0.1.jar",
          "size": 397256,
          "sha512": "df0389019b67bda6429d5812289de37b9d7d175683b622351d16cdc4fe94fffe51a5d79a207c0daa39b920513c257423699939493095fdcfa90794ee32e210d7",
          "sha256": "970f9bbe1df8742f1c7b085ccb485d650cbdf23f5e409bbd8c0a88f0902cba7e",
          "sha1": "4603e3ee97c0706c2a850a5856b8b3823af1d348",
          "md5": "918af88e594737c65ead07856d006db6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manaita_plus_general-2.0.1-sources.jar",
          "url": "manaita_plus_general-2.0.1-sources.jar",
          "size": 313367,
          "sha512": "821ce426b2898d5b68c952d3abd06b5610f9d88c23eccad208fb779bc9b5e3effaf5a70844a21f72a704f2b65e2835a4f59cb06c4e71daff0a1090442c5d20e9",
          "sha256": "9c3fd9748547e2ff65c4b45dea5fb229d53cb17d05c47396329021c0d262aa8e",
          "sha1": "cc1b0ffe4832cabb8a97e2caa23cdcdffa6cfd96",
          "md5": "ee233c5b932fba344e0b467dec3d32a3"
        }
      ]
    }
  ]
}
