{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyoubo",
    "module": "ManaitaPlusGeneral",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ManaitaPlusGeneral-2.3.0-1.20.1-forge.jar",
          "url": "ManaitaPlusGeneral-2.3.0-1.20.1-forge.jar",
          "size": 499265,
          "sha512": "2b6fc3965a191ba07a597dd778a91991e5e8b5c5806fe733ac6afca0348de95a354d1275fb20ab7f7f272d5e109a407826a87891f95a5d4d419cb3bf87206454",
          "sha256": "6fc55cc224f13d14aaba5aa9ff65e69b164e3e6ac3e965c07e8f0881ee20a9cb",
          "sha1": "c2119fc2e9b5d49f288755a4e12e575913bf8379",
          "md5": "ede9a85c771a091894d0e510fa7fec85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.19_mapped_official_1.20.1_at_c4938dc61b17c2dcbc1bd616cfe960b7b16cee3e"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "strictly": "15.20.0.130_mapped_official_1.20.1",
            "requires": "15.20.0.130_mapped_official_1.20.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-forge",
          "version": {
            "strictly": "5.14.1+1.20.1_mapped_official_1.20.1",
            "requires": "5.14.1+1.20.1_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "ManaitaPlusGeneral-2.3.0-1.20.1-forge.jar",
          "url": "ManaitaPlusGeneral-2.3.0-1.20.1-forge.jar",
          "size": 499265,
          "sha512": "2b6fc3965a191ba07a597dd778a91991e5e8b5c5806fe733ac6afca0348de95a354d1275fb20ab7f7f272d5e109a407826a87891f95a5d4d419cb3bf87206454",
          "sha256": "6fc55cc224f13d14aaba5aa9ff65e69b164e3e6ac3e965c07e8f0881ee20a9cb",
          "sha1": "c2119fc2e9b5d49f288755a4e12e575913bf8379",
          "md5": "ede9a85c771a091894d0e510fa7fec85"
        }
      ]
    }
  ]
}
